#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : mpv
Version  : 20.08.09
Release  : 20
URL      : file:///insilications/build/clearlinux/packages/mpv/mpv-20.08.09.zip
Source0  : file:///insilications/build/clearlinux/packages/mpv/mpv-20.08.09.zip
Summary  : mpv media player client library
Group    : Development/Tools
License  : GPL-2.0
BuildRequires : ImageMagick-dev
BuildRequires : LuaJIT
BuildRequires : SDL2-dev
BuildRequires : Sphinx
BuildRequires : Vulkan-Headers-dev
BuildRequires : Vulkan-Loader-dev
BuildRequires : alsa-lib-dev
BuildRequires : alsa-lib-lib
BuildRequires : binutils
BuildRequires : binutils-dev
BuildRequires : binutils-staticdev
BuildRequires : brotli
BuildRequires : brotli-dev
BuildRequires : brotli-staticdev
BuildRequires : bzip2
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : cairo
BuildRequires : cairo-dev
BuildRequires : cuda
BuildRequires : cuda-dev
BuildRequires : cuda-staticdev
BuildRequires : expat-dev
BuildRequires : expat-staticdev
BuildRequires : ffmpeg
BuildRequires : ffmpeg-dev
BuildRequires : ffmpeg-staticdev
BuildRequires : findutils
BuildRequires : fontconfig-dev
BuildRequires : fontconfig-staticdev
BuildRequires : freetype-dev
BuildRequires : freetype-staticdev
BuildRequires : fribidi-dev
BuildRequires : fribidi-staticdev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-libs-math
BuildRequires : gcc9
BuildRequires : gcc9-dev
BuildRequires : gcc9-libs-math
BuildRequires : glib
BuildRequires : glib-dev
BuildRequires : glib-staticdev
BuildRequires : glibc
BuildRequires : glibc-dev
BuildRequires : glibc-staticdev
BuildRequires : gmp
BuildRequires : gmp-dev
BuildRequires : gmp-staticdev
BuildRequires : gnutls
BuildRequires : gnutls-dev
BuildRequires : gnutls-staticdev
BuildRequires : graphite-dev
BuildRequires : graphite-staticdev
BuildRequires : gsm-dev
BuildRequires : gsm-staticdev
BuildRequires : harfbuzz-dev
BuildRequires : harfbuzz-staticdev
BuildRequires : ladspa_sdk
BuildRequires : ladspa_sdk-bin
BuildRequires : ladspa_sdk-dev
BuildRequires : ladspa_sdk-lib
BuildRequires : lcms2
BuildRequires : lcms2-dev
BuildRequires : libX11-dev
BuildRequires : libaom-dev
BuildRequires : libaom-staticdev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libass-dev
BuildRequires : libass-lib
BuildRequires : libass-staticdev
BuildRequires : libatomic_ops-dev
BuildRequires : libatomic_ops-staticdev
BuildRequires : libbluray
BuildRequires : libbluray-dev
BuildRequires : libbluray-staticdev
BuildRequires : libcap-ng-dev
BuildRequires : libconfig-dev
BuildRequires : libconfig-staticdev
BuildRequires : libdav1d-dev
BuildRequires : libdav1d-staticdev
BuildRequires : libdrm
BuildRequires : libdrm-dev
BuildRequires : libdrm-lib
BuildRequires : libdrm-staticdev
BuildRequires : libfdk_aac-dev
BuildRequires : libfdk_aac-staticdev
BuildRequires : libffado
BuildRequires : libffado-dev
BuildRequires : libffado-python3
BuildRequires : libffi-dev
BuildRequires : libffi-staticdev
BuildRequires : libidn2
BuildRequires : libidn2-dev
BuildRequires : libidn2-staticdev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libmp3lame-dev
BuildRequires : libmp3lame-lib
BuildRequires : libmp3lame-staticdev
BuildRequires : libogg-dev
BuildRequires : libogg-staticdev
BuildRequires : libpng-dev
BuildRequires : libpng-staticdev
BuildRequires : libsrt-dev
BuildRequires : libsrt-staticdev
BuildRequires : libtasn1-dev
BuildRequires : libtasn1-staticdev
BuildRequires : libtheora-dev
BuildRequires : libtheora-staticdev
BuildRequires : libunistring-dev
BuildRequires : libunistring-staticdev
BuildRequires : libva
BuildRequires : libva-dev
BuildRequires : libva-lib
BuildRequires : libvapoursynth
BuildRequires : libvapoursynth-dev
BuildRequires : libvapoursynth-python
BuildRequires : libvapoursynth-python3
BuildRequires : libvapoursynth-staticdev
BuildRequires : libvdpau
BuildRequires : libvdpau-dev
BuildRequires : libvidstab-dev
BuildRequires : libvidstab-staticdev
BuildRequires : libvorbis-dev
BuildRequires : libvorbis-staticdev
BuildRequires : libvpx-dev
BuildRequires : libvpx-staticdev
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : libx264-dev
BuildRequires : libx264-staticdev
BuildRequires : libx265
BuildRequires : libx265-dev
BuildRequires : libx265-lib
BuildRequires : libx265-staticdev
BuildRequires : libxml2-dev
BuildRequires : libxml2-staticdev
BuildRequires : libxvid
BuildRequires : libxvid-dev
BuildRequires : libxvid-staticdev
BuildRequires : libzimg-dev
BuildRequires : libzimg-staticdev
BuildRequires : mediasdk-dev
BuildRequires : mesa
BuildRequires : mesa-dev
BuildRequires : mesa-lib
BuildRequires : mm-common-dev
BuildRequires : nasm
BuildRequires : nasm-bin
BuildRequires : nettle
BuildRequires : nettle-dev
BuildRequires : nettle-staticdev
BuildRequires : numactl
BuildRequires : numactl-dev
BuildRequires : numactl-staticdev
BuildRequires : nv-codec-headers
BuildRequires : nv-codec-headers-dev
BuildRequires : nvidia
BuildRequires : nvidia-dev
BuildRequires : opencl-headers
BuildRequires : opencl-headers-dev
BuildRequires : openjpeg-dev
BuildRequires : openjpeg-staticdev
BuildRequires : openssl
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : opus-dev
BuildRequires : opus-staticdev
BuildRequires : orc-dev
BuildRequires : orc-staticdev
BuildRequires : p11-kit
BuildRequires : p11-kit-dev
BuildRequires : pcre-dev
BuildRequires : pcre-staticdev
BuildRequires : pixman
BuildRequires : pixman-dev
BuildRequires : pixman-staticdev
BuildRequires : pkg-config
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(Magick++)
BuildRequires : pkgconfig(MagickCore)
BuildRequires : pkgconfig(MagickWand)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(aom)
BuildRequires : pkgconfig(atomic_ops)
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(bzip2)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-egl)
BuildRequires : pkgconfig(cairo-fc)
BuildRequires : pkgconfig(cairo-ft)
BuildRequires : pkgconfig(cairo-gl)
BuildRequires : pkgconfig(cairo-glx)
BuildRequires : pkgconfig(cairo-gobject)
BuildRequires : pkgconfig(cairo-pdf)
BuildRequires : pkgconfig(cairo-png)
BuildRequires : pkgconfig(cairo-ps)
BuildRequires : pkgconfig(cairo-script)
BuildRequires : pkgconfig(cairo-svg)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(cairo-xcb-shm)
BuildRequires : pkgconfig(cairo-xlib)
BuildRequires : pkgconfig(cairo-xlib-xcb)
BuildRequires : pkgconfig(cairo-xlib-xrender)
BuildRequires : pkgconfig(dav1d)
BuildRequires : pkgconfig(dbus-c++-1)
BuildRequires : pkgconfig(dbus-c++-ecore-1)
BuildRequires : pkgconfig(dbus-c++-glib-1)
BuildRequires : pkgconfig(dri)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(fdisk)
BuildRequires : pkgconfig(fdk-aac)
BuildRequires : pkgconfig(ffnvcodec)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(fribidi)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(glesv1_cm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gmodule-2.0)
BuildRequires : pkgconfig(gmodule-export-2.0)
BuildRequires : pkgconfig(gmodule-no-export-2.0)
BuildRequires : pkgconfig(gmp)
BuildRequires : pkgconfig(gmpxx)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(graphite2)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(haisrt)
BuildRequires : pkgconfig(hogweed)
BuildRequires : pkgconfig(lame)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libarchive)
BuildRequires : pkgconfig(libass)
BuildRequires : pkgconfig(libavcodec)
BuildRequires : pkgconfig(libavdevice)
BuildRequires : pkgconfig(libavfilter)
BuildRequires : pkgconfig(libavformat)
BuildRequires : pkgconfig(libavutil)
BuildRequires : pkgconfig(libbluray)
BuildRequires : pkgconfig(libbrotlicommon)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(libbrotlienc)
BuildRequires : pkgconfig(libconfig)
BuildRequires : pkgconfig(libconfig++)
BuildRequires : pkgconfig(libcrypto)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_amdgpu)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libdrm_nouveau)
BuildRequires : pkgconfig(libdrm_radeon)
BuildRequires : pkgconfig(libdvbv5)
BuildRequires : pkgconfig(libffado)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libidn2)
BuildRequires : pkgconfig(libjpeg)
BuildRequires : pkgconfig(libkms)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libmfx)
BuildRequires : pkgconfig(libopenjp2)
BuildRequires : pkgconfig(libpcre)
BuildRequires : pkgconfig(libpcre16)
BuildRequires : pkgconfig(libpcre32)
BuildRequires : pkgconfig(libpcrecpp)
BuildRequires : pkgconfig(libpcreposix)
BuildRequires : pkgconfig(libplacebo)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpostproc)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(librtmp)
BuildRequires : pkgconfig(libssl)
BuildRequires : pkgconfig(libswresample)
BuildRequires : pkgconfig(libswscale)
BuildRequires : pkgconfig(libtasn1)
BuildRequires : pkgconfig(libturbojpeg)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libva-glx)
BuildRequires : pkgconfig(libva-wayland)
BuildRequires : pkgconfig(libva-x11)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libwebpdecoder)
BuildRequires : pkgconfig(libwebpdemux)
BuildRequires : pkgconfig(libwebpmux)
BuildRequires : pkgconfig(libxml++-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(luajit)
BuildRequires : pkgconfig(mm-common-libstdc++)
BuildRequires : pkgconfig(mm-common-util)
BuildRequires : pkgconfig(mount)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(numa)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(openssl)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(osmesa)
BuildRequires : pkgconfig(p11-kit-1)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(python-3.8)
BuildRequires : pkgconfig(python-3.8-embed)
BuildRequires : pkgconfig(readline)
BuildRequires : pkgconfig(sdl2)
BuildRequires : pkgconfig(smartcols)
BuildRequires : pkgconfig(speex)
BuildRequires : pkgconfig(srt)
BuildRequires : pkgconfig(theora)
BuildRequires : pkgconfig(uchardet)
BuildRequires : pkgconfig(uuid)
BuildRequires : pkgconfig(vapoursynth)
BuildRequires : pkgconfig(vapoursynth-script)
BuildRequires : pkgconfig(vdpau)
BuildRequires : pkgconfig(vidstab)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(vpx)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x264)
BuildRequires : pkgconfig(x265)
BuildRequires : pkgconfig(xatracker)
BuildRequires : pkgconfig(xdg-desktop-portal)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xscrnsaver)
BuildRequires : pkgconfig(zimg)
BuildRequires : pkgconfig(zlib)
BuildRequires : pulseaudio-dev
BuildRequires : python3-core
BuildRequires : python3-dev
BuildRequires : python3-staticdev
BuildRequires : rtmpdump
BuildRequires : rtmpdump-dev
BuildRequires : rtmpdump-staticdev
BuildRequires : snappy-dev
BuildRequires : snappy-staticdev
BuildRequires : speex-dev
BuildRequires : speex-staticdev
BuildRequires : speexdsp-dev
BuildRequires : speexdsp-staticdev
BuildRequires : texinfo
BuildRequires : uchardet
BuildRequires : uchardet-dev
BuildRequires : util-linux
BuildRequires : util-linux-dev
BuildRequires : util-linux-staticdev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
# Ignore missing build ids
%undefine _missing_build_ids_terminate_build
# Disable automatic requeriments processing
AutoReq: no
# Disable automatic provides processing
AutoProv: no

%description
TA ("Tree Allocator") is a wrapper around malloc() and related functions,
adding features like automatically freeing sub-trees of memory allocations if
a parent allocation is freed.

%prep
%setup -q -n mpv-20.08.09
cd %{_builddir}/mpv-20.08.09

%build
unset http_proxy
unset https_proxy
unset no_proxy
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596975320
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
## altflags1 content
export CFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
# -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
# gcc: -feliminate-unused-debug-types -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common  -fno-plt -fipa-pta
export CXXFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe"
#
export FCFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export FFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
export CFFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe"
#
export LDFLAGS="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -flto=16 -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe /usr/lib64/libgbm.so /usr/lib64/libva-drm.so /usr/lib64/libva.so -L/usr/lib64"
#
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export LD_LIBRARY_PATH="/usr/cuda/lib64:/usr/nvidia/lib64:/usr/nvidia/lib:/usr/nvidia/lib/vdpau:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
export PATH="/usr/cuda/bin:/usr/nvidia/bin:$PATH"
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig:/usr/lib/pkgconfig"
#export CCACHE_DISABLE=1
## altflags1 end
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1596975320
rm -rf %{buildroot}
## install_prepend content
# exit 1
## install_prepend end
%make_install

%files
%defattr(-,root,root,-)
